### ISSUE TITLE
does not work when label already exists in English (fallback)

### ISSUE THREAD

**Issue by hsarrazin** [joernhees/wikidata-altLabels#2]
Hello, 
My main language is french, and I work on adding fr labels on people, mainly...

Since the automatic English fallback has been introduced on wd, this fantastic tool does not work for people who work in other languages, if the english label already exists, as the fallback is considered a label. see https://www.wikidata.org/wiki/User_talk:Joern#Altlabel_not_working_when_there_is_English_fallback

Could you please correct it, so as the fallback label were not considered label in the work language. 

Thanks a lot for this brilliant tool... :)

**Comment by joernhees** [comment]
closed in 7386ac3d38be7ddc257f428bab0b1bfd6820d177, version 3.1.0
